### ISSUE TITLE
Installation instructions correct?

### ISSUE THREAD

**Issue by dennismonsewicz** [dirkaholic/vagrant-php-dev-box#14]
I installed the vagrant box the way it says in the README, however, when I visit http://localhost:8181/app_dev.php in my browser, I get a `no data received` error

**Comment by brickgale** [comment]
having same problem. don't know if it's running the way it should be...

**Comment by dirkaholic** [comment]
Just upgraded to a new version using the ansible privisioner and therefor will close this issue.
