### ISSUE TITLE
PHP apt repository is deprecated

### ISSUE THREAD

**Issue by johnmarinelli** [dirkaholic/vagrant-php-dev-box#27]
The apt repo for PHP:
`apt_repository: repo='ppa:ondrej/php5-5.6'`

https://github.com/dirkaholic/vagrant-php-dev-box/blob/master/playbooks/tasks/php.yml#L3

is deprecated:
<img width="724" alt="screen shot 2016-12-19 at 10 29 14 am" src="https://cloud.githubusercontent.com/assets/3382949/21324237/ba86577a-c5d5-11e6-8bac-3bdb6b9cc351.png">

I've updated it to point here:
https://launchpad.net/~ondrej/+archive/ubuntu/php

And it works for me.

**Comment by dirkaholic** [comment]
Fixed with #29 .
