### ISSUE TITLE
Role-based setup

### ISSUE THREAD

**Issue by mraerino** [dirkaholic/vagrant-php-dev-box#30]
Would you consider accepting a pull-request, that would refactor the playbook to use roles instead of task includes?

Right now, if I want to use just parts of your playbook, I need to copy most of the `vagrant.yml` playbook, instead of just including some roles.
The advantage would be having handlers, templates and tasks bundled together in the role definition.

**Comment by dirkaholic** [comment]
Sure, feel free to open a PR. I think using roles is the better way anyways.

**Comment by dirkaholic** [comment]
Hi @mraerino, I opened #31 in order to refactor the playbooks into roles. Maybe you can test it ?
